"""empty message

Revision ID: 5b430b830a84
Revises: c8ab432d8a20
Create Date: 2016-02-20 19:43:43.299724

"""

# revision identifiers, used by Alembic.
revision = '5b430b830a84'
down_revision = 'c8ab432d8a20'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('is_resturant', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'is_resturant')
    ### end Alembic commands ###
