"""empty message

Revision ID: 8fd9092f7d83
Revises: None
Create Date: 2016-02-20 16:40:11.179531

"""

# revision identifiers, used by Alembic.
revision = '8fd9092f7d83'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetups',
    sa.Column('id', sa.String(length=9), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('organizer', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meetup_id', sa.String(length=9), nullable=True),
    sa.Column('tripadvisor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timeslots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meetup_id', sa.String(length=9), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('votes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meetup_id'], ['meetups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timeslots')
    op.drop_table('activities')
    op.drop_table('meetups')
    ### end Alembic commands ###
