"""empty message

Revision ID: bc6f5736f318
Revises: 5b430b830a84
Create Date: 2016-02-20 19:57:29.027278

"""

# revision identifiers, used by Alembic.
revision = 'bc6f5736f318'
down_revision = '5b430b830a84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('is_restaurant', sa.Boolean(), nullable=True))
    op.drop_column('activities', 'is_resturant')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('is_resturant', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('activities', 'is_restaurant')
    ### end Alembic commands ###
