"""empty message

Revision ID: c8ab432d8a20
Revises: deee47c866e1
Create Date: 2016-02-20 19:25:36.655938

"""

# revision identifiers, used by Alembic.
revision = 'c8ab432d8a20'
down_revision = 'deee47c866e1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('web_url', sa.String(length=255), nullable=True))
    op.drop_column('activities', 'tripadvisor_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('tripadvisor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('activities', 'web_url')
    ### end Alembic commands ###
